# Understanding and learning Numpy library

Importing the Numpy library

In [1]:
import numpy as np

Initialising the array

In [4]:
# 1d arrays
a_1d = np.array([1,2,3], dtype="int16")
b_1d  = np.array([4,5,6])

# 2d arrays
c_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d_2d = np.array([[11,12,13],[14,15,16],[17,18,19]])
f_2d = np.array([[1.0,2.0,3.0],[2.3,3.4,5.6]])

# 3d arrays
e_3d = np.array([[['1', '#', '#'], ['#', '#', '#'], ['#', '#', '#']],
 [['#', '#', '#'], ['#', '#', 3], ['#', '#', '#']],
 [[4.5, '#', '#'], ['#', '#', '#'], ['A', '#', '#']]])

Getting more information about the arrays

In [70]:
print("Number of rowsXcolumns(r*c) in the matrix/array:")
#The "shape" of the array is the (rows,columns)
print(a_1d.shape)    #here 3 columns and only 1 row so "(3,)"
print(b_1d.shape)
print(c_2d.shape)    #here 3 columns and 3 rows so "(3,3)"
print(d_2d.shape)
print(f_2d.shape)   # here 2 rows and 3 columns so (2,3)

print()

print("The number of elements in the array:")
print(a_1d.size)     #there are only 3 elements in the array
print(b_1d.size)
print(c_2d.size)     #this array has 3 rows and 3 columns so 3X3 = 9 elemnts
print(d_2d.size)

print()

print("Item size/datatype size:")
print(a_1d.itemsize)     #this array is of type int = 4 bytes but since a_1d is "dtype=int16" the int = 2 bytes
print(b_1d.itemsize)     #this is also type int so int = 4 bytes
print(c_2d.itemsize)
print(d_2d.itemsize)
print(e_3d.itemsize)

print()

print("Total amount of byte size occupied in memory (that is, number of elements * size of the datatype):")
print(a_1d.size * a_1d.itemsize)    # here the size of "a_1d" is 2 bytes(because datatype = "int16") and "a_1d" has 3 elements so 2*3 = 6
print(a_1d.nbytes)
print(b_1d.nbytes)                  #here the size of "b_1d" is 4 bytes(because datatype = "int32") and "b_1d" has 3 elemnts so 4*3 = 12

print()

print("Dimension of the matrix/array:")
print(a_1d.ndim)   #"a_1d" is an one dimensional array since it has only 1 row and contains only columns: 3
print(b_1d.ndim)   
print(c_2d.ndim)   #"c_2d" is a two dimensional array since it contains multiple columns and multiple rows here 3 columns and 3 rows (3,3) and these 2d arrays also called as "sheets" : 3X3
print(d_2d.ndim)
print(e_3d.ndim)   #"d_3d" is a three dimensional array which has multiple rows, multiple columns and multiple depth("I'm not sure what is term after row and column so i am using the term "depth"), 3d arrays are also called as "workbooks": 3X3X3

Number of rowsXcolumns(r*c) in the matrix/array:
(3,)
(3,)
(3, 3)
(3, 3)
(2, 3)

The number of elements in the array:
3
3
9
9

Item size/datatype size:
2
4
4
4
128

Total amount of byte size occupied in memory (that is, number of elements * size of the datatype):
6
6
12

Dimension of the matrix/array:
1
1
2
2
3


Arrays numericals and computation

In [57]:
#simple matrix addition
c = a_1d + b_1d
print(f" a_1d + b_1d = {c} \n")

#simple matrix multiplication
d  = c_2d * d_2d
print(d)

 a_1d + b_1d = [5 7 9] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [65]:
print(c_2d[:,0:2]*d_2d[:,0:2])
print()
print(e_3d)

[[ 11  24]
 [ 56  75]
 [119 144]]

[[['1' '#' '#']
  ['#' '#' '#']
  ['#' '#' '#']]

 [['#' '#' '#']
  ['#' '#' '3']
  ['#' '#' '#']]

 [['4.5' '#' '#']
  ['#' '#' '#']
  ['A' '#' '#']]]


Matrix manipulation

In [12]:
#changing the 2nd row 2 column element in a matrix
c_2d[1,1] = 10
print(c_2d)

#changing the 2nd matrix 1st row 3rd column element in a 3D array
print(e_3d)
e_3d[1,0,2] = 102
print(e_3d[1,0,2])

[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
[[['1' '#' '#']
  ['#' '#' '#']
  ['#' '#' '#']]

 [['#' '#' '#']
  ['#' '#' '3']
  ['#' '#' '#']]

 [['4.5' '#' '#']
  ['#' '#' '#']
  ['A' '#' '#']]]
102


Initialising all types of arrays/matrix

In [24]:
#creating a matrix/array with all zeros
zeros_2d = np.zeros((3,3))

#Creating an array/matrix with all ones
ones_2d = np.ones((2,3))

#Creating an array/matrix with desired elements(integers,strings,etc)
full_1d = np.full((7), 7)
#fuul_1d = np.full(a_1d.shape, 7)

#creating an array/matrix of an identical shape to previously created elements 
full_like_2d = np.full_like(c_2d, 8)

#creating an array/matrix of random float numbers
rand_deci = np.random.rand(3,3)                       #gives random decimal values between 0 to 1
#rand_deci = np.random.random_shape(c_2d)

#creating an array/matrix for random integer values
rand_int = np.random.randint(0, 10, size=(3,3))               #give random integer values between 0 to 10(10 is excluded) in the shape == size = (3,3)

#creating an identity matrix
ident_2d = np.identity(3)

#creating and repeating a pattern
arr = np.array([[1,2,3]])
repeat_2d_vert = np.repeat(arr, 3, axis=0)
repeat_2d_hori = np.repeat(arr, 3, axis=1)


print(zeros_2d,"\n")
print(ones_2d, "\n")
print(full_1d, "\n")
print(full_like_2d, "\n")
print(rand_deci ,"\n")
print(rand_int ,"\n")
print(ident_2d ,"\n")
print(repeat_2d_vert ,"\n")
print(repeat_2d_hori ,"\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[7 7 7 7 7 7 7] 

[[8 8 8]
 [8 8 8]
 [8 8 8]] 

[[0.1481571  0.26228127 0.98629248]
 [0.71913054 0.31505014 0.21138415]
 [0.89986729 0.33639481 0.28251627]] 

[[4 5 0]
 [0 1 4]
 [4 6 1]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1 2 3]
 [1 2 3]
 [1 2 3]] 

[[1 1 1 2 2 2 3 3 3]] 



# Challange problem

##### To print a matrix with a give pattern

In [30]:
chal = np.full((5,5), 1)
chal[1:4,1:4] = 0
chal[2,2] = 9
print(chal)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Copying two arrays/matrix

In [2]:
aa = np.array([1,2,3])
bb = aa
bb[0] = 100
print(aa == bb)    #this make the direct copy of a and b is stored in the same memory location of a so if any changes are made to b then it will reflect in a

#the right way of copying arrays/matrix
cc = np.array([4,5,6])
dd = cc.copy()
dd[0] = 200
print(cc == dd)


[ True  True  True]
[False  True  True]


## Mathematics

Regular matrix mathematics

In [39]:
print(aa + 2 ,"\n")
print(bb - 3 ,"\n")
print(cc * 7 ,"\n")
print(dd / 10 ,"\n")
print(bb ** 2 ,"\n")

[102   4   5] 

[97 -1  0] 

[28 35 42] 

[20.   0.5  0.6] 

[10000     4     9] 



trigonometry

In [42]:
print(np.sin(aa))
print(np.tan(aa))

[-0.50636564  0.90929743  0.14112001]
[-0.58721392 -2.18503986 -0.14254654]


Linear Algebra

In [49]:
aa = np.full((2,3), 2)
bb = np.full((3,4), 2)

#error handling for incorrect semantics
try:
    print(aa * bb)
except:
    print("This operation can not be done because semantic error")

#correct semantics
print(np.matmul(aa,bb), "\n")

aa = np.identity(3)
print(np.linalg.det(aa), "\n")      #to determine the identity matrix's determinante


This operation can not be done because semantic error
[[12 12 12 12]
 [12 12 12 12]] 

1.0 



Statistics

In [ ]:
aa = np.array([[1,2,3]])
bb = np.repeat(aa, 3, axis= 0).copy()
bb[1,:] = bb[1,:] + 2
bb[2,:] = bb[2,:] + 4
bb


ee = np.min(bb)
print(ee, "\n")

ee = np.min(bb,axis=1)
print(ee, "\n")

ee = np.max(bb, axis = 1)
print(ee, "\n")

ee = np.mean(bb)
print(ee, "\n")

ee = np.median(bb)
print(ee, "\n")

ee  = np.sum(bb)
print(ee, "\n")

ee = np.sum(bb, axis = 0) #sums all the elemnts in the matrix going vertically downward
print(ee)


1 

[1 3 5] 

[3 5 7] 

4.0 

4.0 

36 

[ 9 12 15]


Reordering Matrices

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

after = before.reshape((4,2))    #reshaping it into a 2D array
print(after, "\n")

after = after.reshape((2,2,2))  #reshaping it into a 3D array
print(after)

after = after.repeat(3, axis=0)  #This type of repeat also works, similar to previous repeat function
#print(after)

#stacking and concatinating matrix
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2]))
print(np.hstack([v1,v2]))


(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


### Miscellaneous and advanced features

Loading data from files

In [50]:
read = np.genfromtxt("data.txt", delimiter=",")
print(read)

read = np.array(read).astype(int)
print(read)

#read = read.reshape(1,54)   #reshaping it into a 1D array
#print(read)


[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


Advanced indexing

In [37]:
arr = read[read > 50]   #all the elements above 50
arr[[0,4,8]]            #elemnts at indices 0,4 and 8

array([196,  55,  88])

Boolean masking

In [65]:
arr = read[read > 50]
print(arr, "\n")

#for each element is in a column is there any element in the given column that it is greater than the given element(here we have used 50)
arr = np.any(read > 50, axis=0) 
print(arr, "\n")

#for each elemnt in a column is there any element in the row that is greater than aa given number
arr = np.any(read > 50, axis = 1)
print(arr, "\n")

#for in each column are all the elements in the column greater than a given number
arr = np.all(read > 50, axis = 0)
print(arr, "\n")

#print(read)
print(read[(read > 50) & (read < 100)], "\n")       #elements that are greater than 50 but less than 100
print((read[~(read > 50) & (read < 100)]), "\n")     #elements that are not("~") greater than 50 and less than 100


[196  75 766  75  55 999  78  76  88] 

[False False False False  True  True False  True  True False False False
 False False False False  True  True] 

[ True  True  True] 

[False False False False  True False False False False False False False
 False False False False False False] 

[75 75 55 78 76 88] 

[ 1 13 21 11  4  3 34  6  7  8  0  1  2  3  4  5  3 42 12 33  4  6  4  3
  4  5  6  7  0 11 12  1 22 33 11 11  2  1  0  1  2  9  8  7  1] 



### Challenge 2

##### To print the diagonal elements int a given matrix

In [70]:
arr = np.random.randint(0,10, size=(5,5))
arr_1 = np.random.rand(3,3)
print(arr, "\n")
print("Diagonal elements of the matrix arr:", arr[[0,1,2,3,4],[0,1,2,3,4]], "\n")
print(arr_1, "\n")

[[5 8 9 6 5]
 [1 2 9 2 5]
 [9 6 6 1 3]
 [8 4 9 5 3]
 [0 0 0 0 3]] 

Diagonal elements of the matrix arr: [5 2 6 5 3] 

[[0.28769399 0.8796998  0.31527476]
 [0.10945937 0.20089167 0.45835443]
 [0.7798324  0.51740306 0.73531621]] 

